### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by vagarwal77** [mdsol/rwslib#112] opened 2021-04-06 21:33 UTC
I am trying to create RWS connection to Rave
https://xxx-innovate.imedidata.com/apps/EDC and getting below error with all the combinations. 

#rws_connection = RWSConnection('https://xxx-innovate.imedidata.com', 'xxxx', 'yyyy')
#rws_connection = RWSConnection('https://xxx-innovate.imedidata.com/apps/edc/api/v2', 'xxxx', 'yyyy')
#rws_connection = RWSConnection('https://xxx-innovate.imedidata.com/apps/edc', 'xxxx', 'yyyy')

raise RWSException("IIS Error", r.text)

I can login to web instance successfully with the same credential.  Please suggest how to create connection as i had tried all options documented at https://rwslib.readthedocs.io/en/latest/getting_started.html?highlight=RWSException#error-handling

**Comment by iansparks** [comment] 2021-04-06 22:18
@vagarwal77 that looks like you are trying to connect with **iMedidata** Credentials. RWS works only with Rave Classic credentials.

If you go to the web instance and you see a page like this to log in then you are using iMedidata credentials. **RWS does not work with these credentials**

![image](https://user-images.githubusercontent.com/16936481/113785073-54af5a80-972e-11eb-83cb-87e99f6b589f.png)



If you go to the web instance and you see a page like this and can log in then you are using CLASSIC credentials. These are the ones you want and the **only ones** that work with RWS:

![image](https://user-images.githubusercontent.com/16936481/113784980-2a5d9d00-972e-11eb-8068-4ea3fb52d7bf.png)

**Comment by vagarwal77** [comment] 2021-04-06 23:56
Thanks @iansparks . I have only iMedidata credentials.
I am still not clear on differences between iMedidata and Medidata Rave. 
Is there a way to access iMedidata also over API endpoints?

**Comment by iansparks** [comment] 2021-04-07 07:54
There are some iMedidata APIs but these only relate to data held in iMedidata (users, sites, studies etc) not clinical data.

The iMedidata APIs are all accessed via MAuth which is based on a token, not on a username/password. If you want to do anything with RWS and Rave clinical data then you need a Rave classic account. You can also use RWS with MAuth credentials but these must still be related to a Rave classic user in the Rave system so there is no getting away from needing a Rave Classic account, sorry.

**Comment by vagarwal77** [comment] 2021-04-09 02:13
Thanks for all the help @iansparks  I have made all the progress and can get and post except one below issue - 

I am trying to post clinical Data with  rws_connection.send_request(PostDataRequest(data)) but getting below error...
rwslib.rwsobjects.RWSException: Unit Dictionary does not exist

Not sure whether i am missing any thing in the xml. Below XML has been replaced with dummy values

![image](https://user-images.githubusercontent.com/46463536/114119119-0b8b1200-98b8-11eb-9dfb-3f720f5a16c6.png)

<ODM FileType="Transactional" FileOID="232323-682e-421b-bbd6-4a41e223df27"
     CreationDateTime="2021-04-08T16:20:13.453-00:00" ODMVersion="1.3"
     xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xmlns="http://www.cdisc.org/ns/odm/v1.3">     
    <ClinicalData StudyOID="STUDYTEST(DEV)" MetaDataVersionOID="212">
        <SubjectData SubjectKey="123-2">
            <SiteRef LocationOID="00000"/>
            <StudyEventData StudyEventOID="SCRN" StudyEventRepeatKey="1">
                <FormData FormOID="VS_GEN_U01" FormRepeatKey="1">
                    <ItemGroupData ItemGroupOID="VS_GEN_U01_LOG_LINE">
                        <ItemData ItemOID="VS_GEN_U01.M_VSPERF" Value="C49488"/>
                        <ItemData ItemOID="VS_GEN_U01.M_VSDAT"  Value="2021-04-06"/>
                        <ItemData ItemOID="VS_GEN_U01.M_VSSTAT_HEIGHT" Value="C49488"/>
                        <ItemData ItemOID="VS_GEN_U01.M_VSORRES_HEIGHT" Value="144.0"/>
                        <ItemData ItemOID="VS_GEN_U01.M_VSSTAT_WEIGHT" Value="C49487"/>
                        <ItemData ItemOID="VS_GEN_U01.M_VSORRES_WEIGHT" IsNull="Yes"/>
                        <ItemData ItemOID="VS_GEN_U01.DX_WEIGHT" IsNull="Yes"/>
                        <ItemData ItemOID="VS_GEN_U01.DX_HEIGHT" Value="133"/>
                    </ItemGroupData>
                </FormData>
            </StudyEventData>
        </SubjectData>
    </ClinicalData>
    </ODM>

**Comment by vagarwal77** [comment] 2021-04-09 02:15
> Thanks for all the help @iansparks I have made all the progress and can get and post except one below issue -
> 
> I am trying to post clinical Data with rws_connection.send_request(PostDataRequest(data)) but getting below error...
> rwslib.rwsobjects.RWSException: Unit Dictionary does not exist
> 
> Not sure whether i am missing any thing in the xml. Below XML has been replaced with dummy values

data = """<ODM FileType="Transactional" FileOID="c6e3404c-682e-421b-bbd6-4a41e223df27"
     CreationDateTime="2021-04-08T16:20:13.453-00:00" ODMVersion="1.3"
     xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xmlns="http://www.cdisc.org/ns/odm/v1.3">     
    <ClinicalData StudyOID="CC-99712-MM-001Test(DEV)" MetaDataVersionOID="235">
        <SubjectData SubjectKey="123-CHAI">
            <SiteRef LocationOID="00000"/>
            <StudyEventData StudyEventOID="SCRN" StudyEventRepeatKey="1">
                <FormData FormOID="VS_GEN_U01" FormRepeatKey="1">
                    <ItemGroupData ItemGroupOID="VS_GEN_U01_LOG_LINE">
                        <ItemData ItemOID="VS_GEN_U01.M_VSPERF" Value="C49488"/>
                        <ItemData ItemOID="VS_GEN_U01.M_VSDAT"  Value="2021-04-06"/>
                        <ItemData ItemOID="VS_GEN_U01.M_VSSTAT_HEIGHT" Value="C49488"/>
                        <ItemData ItemOID="VS_GEN_U01.M_VSORRES_HEIGHT" Value="144.0"/>
                        <ItemData ItemOID="VS_GEN_U01.M_VSSTAT_WEIGHT" Value="C49487"/>
                        <ItemData ItemOID="VS_GEN_U01.M_VSORRES_WEIGHT" IsNull="Yes"/>
                        <ItemData ItemOID="VS_GEN_U01.DX_WEIGHT" IsNull="Yes"/>
                        <ItemData ItemOID="VS_GEN_U01.DX_HEIGHT" Value="133"/>
                    </ItemGroupData>
                </FormData>
            </StudyEventData>
        </SubjectData>
    </ClinicalData>
    </ODM>"""

**Comment by iansparks** [comment] 2021-04-09 08:21
I think one of your fields (height?, weight?) has a Unit Dictionary attached to it. So when you provide a value like "144.0" is that inches? feet? cm? miles? au?

You need a MeasurementUnitRef for it inside your ItemData:

                       <ItemData ItemOID="VSORRES.HEIGHT" Value="144.0">
                            <MeasurementUnitRef MeasurementUnitOID="UNIT_DICTIONARY_NAME.CODED_VALUE"/>  
                       </ItemData>


Can't be 100% sure that is the problem, but that is my guess.

**Comment by vagarwal77** [comment] 2021-04-14 18:14
Thanks @iansparks for help.. 
Thanks a lot for extending all the help. Now, we are able to make the connection over RWS and pull the CRFs.
 
With lab forms, we are getting a strange behavior with GET - 

***Issue with GET- Missing M_LBORRES_HGB_BLOOD value***
We are able to get the questionnaire back successfully but not its clinical data. For example, in “Local Lab Results – Hematology” form, we are getting “M_LBSTAT_HGB_BLOOD” field back in the filled CRF but not the entered “Hemoglobin (HGB), Blood” value as fieldOID – “M_LBORRES_HGB_BLOOD”. We are expecting LB_GEN_U01_G02_V01.M_LBORRES_HGB_BLOOD to be returned with value "14". iMetadata filled form are showing the correct data in UI.

rws_connection.send_request(StudyDatasetRequest(project_name=final, environment_name='DEV', formoid='LB_GEN_U01_G02_V01'))

<ClinicalData StudyOID="xxx" MetaDataVersionOID="235">
    <SubjectData SubjectKey="001">
        <SiteRef LocationOID="00000"/>
        <StudyEventData StudyEventOID="SCRN" StudyEventRepeatKey="1">
            <FormData FormOID="LB_GEN_U01_G02_V01" FormRepeatKey="1">
                <ItemGroupData ItemGroupOID="LB_GEN_U01_G02_V01_LOG_LINE">
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBPERF" Value="C49488"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBDAT" Value="2020-08-01"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.DX_AGE" IsNull="Yes"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_HGB_BLOOD" IsNull="Yes"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_HCT" Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_RBC_BLOOD" Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_WBC_BLOOD" Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_PLAT" Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_MCV"  Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_LYM"  Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_MONO" Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_EOS"  Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_BASO" Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_NEUT" Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_CD19" Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_CD3"  Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_CD4"  Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_CD8"  Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_MCH"  Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.M_LBSTAT_MCHC" Value="C49484"/>
                    <ItemData ItemOID="LB_GEN_U01_G02_V01.X_HIDNLAB"  Value="2021-04-13T10:40:30"/>
                </ItemGroupData>
            </FormData>
        </StudyEventData>
    </SubjectData>
</ClinicalData>

![image](https://user-images.githubusercontent.com/46463536/114759226-e66d2800-9d2b-11eb-8720-f720dcce2890.png)

**Comment by iansparks** [comment] 2021-04-14 20:20
Hi @vagarwal77 I suspect the problem is that the data you want is in the LAB dataset. This comment thread might help you explore this:

https://github.com/mdsol/rwslib/issues/110

My point is you want to get the V_MYSTUDYNAME_Lab view I think. I don't think you can get that with a StudyDatasetRequest but if you make a request to:

GET https://{host}/RaveWebServices/datasets/V_MYSTUDYNAME_Lab.csv 

You can probably get it in CSV format.

**Comment by iansparks** [comment] 2021-05-15 21:02
@vagarwal77 is this still open or can we close this issue?

**Comment by glow-mdsol** [comment] 2021-06-29 08:55
Closing, it's been a while

**Closed as completed by glow-mdsol** 2021-06-29 08:55 UTC
